CREATE OR REPLACE DATABASE discover_handson;

USE SCHEMA discover_handson.public;

CREATE OR REPLACE WAREHOUSE handson_wh 
WITH WAREHOUSE_SIZE = 'X-SMALL';

CREATE STAGE HANDSON_STAGE 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );
	
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
